# Generated by Django 3.2.10 on 2024-01-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_package_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='recommendation',
        ),
    ]
