# Generated by Django 3.2.10 on 2024-01-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_remove_package_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255, verbose_name='Category Heading')),
            ],
        ),
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
        migrations.RemoveField(
            model_name='package',
            name='heading',
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='packages', to='travelapp.category', verbose_name='Category'),
        ),
    ]
