# Generated by Django 3.2.10 on 2024-03-02 07:13

from django.db import migrations, models
import django.db.models.deletion
import travelapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('nameofday', models.CharField(max_length=255, verbose_name='Name of day')),
                ('pickup_location', models.TextField(null=True)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('checkin_time', models.TimeField(null=True)),
                ('accommodation_options', models.TextField(null=True)),
                ('meals_included', models.TextField(null=True)),
                ('activities_included', models.TextField(null=True)),
                ('overnight_stay_location', models.CharField(max_length=100, null=True)),
                ('departure_location', models.CharField(max_length=100, null=True)),
                ('dropoff_location', models.CharField(max_length=100, null=True)),
                ('checkout_time', models.TimeField(null=True)),
                ('package_inclusions', models.TextField(null=True)),
                ('package_exclusions', models.TextField(null=True)),
                ('terms_and_conditions', models.TextField(null=True)),
                ('package', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='days', to='travelapp.package', verbose_name=travelapp.models.Package)),
            ],
        ),
    ]
