# Generated by Django 3.2.10 on 2024-03-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_auto_20240303_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='images',
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
