# Generated by Django 3.2.10 on 2024-03-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0012_auto_20240303_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='images',
        ),
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(max_length=5000, verbose_name='Description'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
