# Generated by Django 3.2.10 on 2024-03-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0014_alter_package_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(max_length=5000, verbose_name='Description'),
        ),
    ]
