# Generated by Django 3.2.10 on 2024-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0019_auto_20240304_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(max_length=7000),
        ),
    ]
