# Generated by Django 3.2.10 on 2024-03-04 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0020_alter_package_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
