# Generated by Django 3.2.10 on 2024-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0021_remove_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
