# Generated by Django 3.2.10 on 2024-03-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0027_auto_20240309_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.FileField(upload_to='package_images/', verbose_name='Image'),
        ),
    ]
