# Generated by Django 3.2.10 on 2024-03-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0028_alter_packageimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(upload_to='package_images/', verbose_name='Image'),
        ),
    ]
