# Generated by Django 3.2.10 on 2024-03-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0031_alter_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageimage',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='Image'),
        ),
    ]
